6 & 7 complete
Connor-Quinny/NC-games pull request #3
Opened 2022-09-28 09:34 UTC by Connor-Quinny

I had already done 6 from earlier

2022-09-28 10:12 UTC, mallionaire requested changes
Nice start! 
I've got. a few tips for you! 
You seem to be getting a few `Each child in a list` warnings, look into these, I suspect it might be the links causing the problem. 

You could use the axios `params` object to tidy up (and DRY up) your api requests if a category is provided. 

Also - the `users` and `games` tags in your nav bar seem unnecessary - will you ever be displaying a list of games, or was this something you copied from an example you've seen in the lecture? 

Also it would be nice to optimistically render the change to the vote, assuming that there will be a success from the api (if you change your internet speed in the network tab on devtools you can see that it takes some time for the vote change to come through)

2022-09-28 10:12 UTC, mallionaire commented on src/Components/ReviewCard.jsx
>      useEffect(() => {
Please extract your api calls into a `utils/api.js`

2022-09-29 14:49 UTC, Augs0 requested changes
Hey Connor, can see lots of great changes made here. One more thing I'd like you to do is add a 404 page for when I go to a non-existent article. Currently, if I do that, I get a page with the labels and an undefined title which is not the best user experience

2022-09-30 10:52 UTC, leekli approved these changes
Well done Connor, you are free to merge this branch.

One point: If I go to a non-existant article in desktop view, I can see the 404 error message, but If I do it in mobile view I can't see the 404 message, just a blank page... I'd have a look at this in your next ticket but for now please do merge tickets 6 & 7 first. :)

2022-09-30 11:03 UTC, merged